### PR TITLE
Add license to project

### PR DESCRIPTION
**Pull request by peeley**
Hello, and thanks for the fantastic project! I've used this software to convert the classic [Boatmurdered](https://lparchive.org/Dwarf-Fortress-Boatmurdered/) LP to EPUB for reading on my Kindle, and it's been a great experience.

I'd love to package this for NixOS via [nixpkgs](https://github.com/NixOS/nixpkgs), but the repository requires all software to be licensed. I'm not sure what your goals/intentions for the project may be, so I figured I'd propose the MIT License as a moderate default.

### CODE REVIEW

**Comment by Arwalk** [comment]
Hi! Thanks! I'm glad at least one person used it. I reread multiple lp's with it myself but had no feedback until then.

The license was indeed missing, thanks for adding it. 

If you read any other lp with this tool, don't hesitate to tell me if something goes wrong!

**Comment by Arwalk** [comment]
Also, could you link me to your work to package it for nix? Im interested.

**Comment by peeley** [comment]
Thanks a ton! Here's the package, in my fork of nixpkgs: https://github.com/peeley/nixpkgs/commit/5ffe61fe02bc896dbbf4b8a9e61646f716ef87a2 . It's not too fancy, since everything is already packaged nicely with poetry here.

Another small ask, if you don't mind - would it be possible to do a version bump, so that the package could be pointed to a tag containing the new license? Just want to make sure that there's zero issues with the nixpkgs maintainers about licensing.

**Comment by Arwalk** [comment]
Sure. Thanks for the link. I'm surprised you still have to set the dependencies in the nixpkg file considering they are already ported by poetry 🤔 . I don't know a lot about nix packaging.

Version bump coming in a few minutes.

**Pull request merged**
